### PR TITLE
Added Flamecord and some [ABANDONNED] tags

### PR DESCRIPTION
**Pull request by SparkGNRK**
Thank you for creating this list, I'm using it a lot!

### CODE REVIEW

**Comment by UeberallGebannt** [comment]
Thank you very much :)
But isn't it called "ABANDONED" instead of "ABANDONNED"?

**Comment by SparkGNRK** [comment]
Oh yeah sorry! English is not my native langage

**Comment by UeberallGebannt** [comment]
Could you add another commit fixing this? I will merge it after that

**Comment by SparkGNRK** [comment]
Done 😀

**Comment by UeberallGebannt** [comment]
Thank you for your help :)

**Pull request merged**
