### PR TITLE
Reorganize and change format

### PR DESCRIPTION
**Pull request by TonimatasDEV**
I think it's more organized this way

The list separated in two "Active" and "Deactive" for users to see the most secure software first.

You can see the result on: https://github.com/TonimatasDEV/server-softwares

For update the RECOMMEND and README is necessary accept this pull request (For the links)

### CODE REVIEW

**Comment by TonimatasDEV** [comment]
You can see the result on: https://github.com/TonimatasDEV/server-softwares

**Comment by UeberallGebannt** [comment]
I really like this setup^^

However there are a few points we need to talk about:

1. The README links are broken now (easy fix).
2. Tunity has an extra dot (easy fix).
3. I'm unsure about the term "Deactive". Shouldn't it be "Inactive" instead? (not sure, not a native speaker)
4. Is a software like Krypton really fitting the vanilla category? It doesn't have most of the vanilla features. Not sure where I'd put it though.

**Comment by TonimatasDEV** [comment]
> I really like this setup^^
> 
> However there are a few points we need to talk about:
> 
> 1. The README links are broken now (easy fix).
> 2. Tunity has an extra dot (easy fix).
> 3. I'm unsure about the term "Deactive". Shouldn't it be "Inactive" instead? (not sure, not a native speaker)
> 4. Is a software like Krypton really fitting the vanilla category? It doesn't have most of the vanilla features. Not sure where I'd put it though.
> 
> Edit: I just noticed what you said in your message about the README/RECOMMENDED so nevermind 1.

1. In future
2. Fixed
3. Fixed (I am Spanish but inactive is more correct)
4. Vanilla is minecraft without mods/plugins. (Link)[https://www.reddit.com/r/Minecraft/comments/26i82p/psa_what_does_vanilla_mean/]

**Comment by TonimatasDEV** [comment]
> I really like this setup^^
> 
> However there are a few points we need to talk about:
> 
> 1. The README links are broken now (easy fix).
> 2. Tunity has an extra dot (easy fix).
> 3. I'm unsure about the term "Deactive". Shouldn't it be "Inactive" instead? (not sure, not a native speaker)
> 4. Is a software like Krypton really fitting the vanilla category? It doesn't have most of the vanilla features. Not sure where I'd put it though.
> 
> Edit: I just noticed what you said in your message about the README/RECOMMENDED so nevermind 1.

The first and second fixed, the fourth according to what I know, a minecraft server counts as vanilla if it doesn't have plugins or mods

**Comment by UeberallGebannt** [comment]
Closes #18

**Pull request merged**
